### PR TITLE
fixes error ReferenceError: afterEach is not defined

### PR DESCRIPTION
**Pull request by cjwilburn**
I was getting this error, and made this change when running chakram locally.

### CODE REVIEW

**Comment by dareid** [comment]
Hi @cjwilburn, thanks for the pull request. AfterEach is defined in the mocha test framework and Chakram relies on this function to alert users to problems with promise usage. 
What version of mocha are you using?

**Comment by cjwilburn** [comment]
@dareid I'm using 2.3.4

**Comment by cjwilburn** [comment]
@dareid when the tests failed, I did notice that it was running in node 0.10.x. I'm using node 4.1.2 (npm v2.14.4).I could be running into issues there. I'll try downgrading my node version to see what happens.

**Comment by dareid** [comment]
I have just updated my versions of node and mocha to match yours and the tests seem to be running correctly. Is there any chance you could run `npm test` for chakram 1.2.1 to see if they run correctly on your machine? 
If they do, any chance you could provide more information on the tests you are running or the command you are running to perform the tests?

**Comment by cjwilburn** [comment]
With the change in the PR on my local, I am indeed getting the same error on `npm test` as the Travis error on those same versions of node. Not sure why I was initially getting this error when the tests were running using `mocha path/to/tests`

**Pull request closed without merging**
