### PR TITLE
json expectation accepts a RegExp

### PR DESCRIPTION
**Pull request by alepez**
So you can do this:

```
expect(res).to.have.json('version', /^v\d\.\d\.\d$/);
```

### CODE REVIEW

**Comment by alepez** [comment]
CI test isn't passing. I'm going to check this.

**Comment by alepez** [comment]
I think this is ready for merging.

**Comment by dareid** [comment]
Great, thanks for the pull. Will go through it tonight :)

**Comment by dareid** [comment]
I added the following test:
```
expect(postRequest).not.to.have.json('json.str', /^not expected$/)
```
which failed. From the look of your code you are not transferring flags to your inner assertion.

**Comment by dareid** [comment]
Closing due to inactivity

**Pull request closed without merging**
