### PR TITLE
Exposing tv4 object

### PR DESCRIPTION
**Pull request by exdis**
Just exposed tv4 object. It allows to use tv4 methods, eg:
```js
var chakram = require('chakram');
chakram.tv4.addFormat(...
```

### CODE REVIEW

**Comment by dareid** [comment]
Thanks for the pull request @exdis. 
During the design of the Chakram library I considered exposing tv4, allowing use of its methods. However, I decided against this as it does not allow tv4 to be changed to another library in future (see #32 for initial doubts). So ideally the methods you require need to be exposed as a facade to the tv4 methods, similar to the current `chakram.addSchema`.  What are your thoughts on this?

**Comment by exdis** [comment]
I agree with you. But in our project we use huge schemas with many params. `tv4.validateResult` gives only first validation error. We extended chakram by adding custom method which uses `tv4.validateMultiple`, but in this case we need to require tv4 into project's dependencies.

If we'll have tv4 exposed by chakram it will be esier to extend chakram functionality.

**Comment by dareid** [comment]
I have raised #38 based on your requirement. Is there any other tv4 methods you need to be exposed? `addFormat`?

**Comment by exdis** [comment]
I think in my case would be enough `addFormat`.

**Comment by dareid** [comment]
Great, I have opened #39 to cover that. Thanks for the suggestions and the feedback :)

**Pull request closed without merging**
